// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import ()

type Product struct {
	Sku     string `json:"sku"`
	Name    string `json:"name"`
	Country string `json:"country"`
}
