// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: product.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products
    (sku, name, country)
VALUES
    ($1,$2, $3)
RETURNING sku, name, country
`

type CreateProductParams struct {
	Sku     string `json:"sku"`
	Name    string `json:"name"`
	Country string `json:"country"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Sku, arg.Name, arg.Country)
	var i Product
	err := row.Scan(&i.Sku, &i.Name, &i.Country)
	return i, err
}
